FROM vektorlab/glibc:latest

ENV NGINX_VERSION 1.6.3

RUN apk add --update make gcc gcc-objc zlib-dev pcre-dev openssl-dev libxslt-dev libxml2-dev geoip-dev perl-dev linux-headers && \
    mkdir -p /usr/local/src && \
    wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -qO - | tar zxf - -C /usr/local/src/ && \
    cd /usr/local/src/nginx-* && \
    ./configure --prefix=/etc/nginx \
                --sbin-path=/usr/sbin/nginx \
                --conf-path=/etc/nginx/nginx.conf \
                --error-log-path=/var/log/nginx/error.log \
                --http-log-path=/var/log/nginx/access.log \
                --pid-path=/var/run/nginx.pid \
                --lock-path=/var/run/nginx.lock \
                --http-client-body-temp-path=/var/cache/nginx/client_temp \
                --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
                --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
                --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
                --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
                --user=nginx \
                --group=nginx \
                --with-http_ssl_module \
                --with-http_realip_module \
                --with-http_addition_module \
                --with-http_sub_module \
                --with-http_geoip_module \
                --with-http_gunzip_module \
                --with-http_gzip_static_module \
                --with-http_random_index_module \
                --with-http_secure_link_module \
                --with-http_stub_status_module \
                --with-http_auth_request_module \
                --with-mail \
                --with-mail_ssl_module \
                --with-file-aio \
                --with-http_spdy_module \
                --with-cc-opt='-g \
                -O2 \
                -fstack-protector \
                --param=ssp-buffer-size=4 \
                -Wformat \
                -Wformat-security \
                -Wp,-D_FORTIFY_SOURCE=2' \
                --with-ld-opt='-Wl,-Bsymbolic-functions \
                -Wl,-z,relro \
                -Wl,--as-needed' \
                --with-ipv6 && \
     make && make install && \
     yum -y -q groupremove 'Development Tools' && \
     yum clean all 

RUN useradd nginx && \
    mkdir -p /var/cache/nginx /var/log/nginx && \
    chown -Rf nginx. /var/cache/nginx /var/log/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl /etc/nginx/certificates

CMD [ "nginx" ]
